// Generated by scripts/build.mjs. Do not edit by hand.
window.__ModuleLoader__.load({
  id: "dsh-notifications",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf, __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: !0 });
}, __copyProps = (to, from, except, desc) => {
  if (from && typeof from == "object" || typeof from == "function")
    for (let key of __getOwnPropNames(from))
      !__hasOwnProp.call(to, key) && key !== except && __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: !0 }) : target,
  mod
)), __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: !0 }), mod);

// src/client.js
var client_exports = {};
__export(client_exports, {
  apply: () => apply,
  createLeaderElector: () => createLeaderElector,
  createNotificationController: () => createNotificationController,
  inject: () => inject
});
module.exports = __toCommonJS(client_exports);
var import_react = __toESM(require("react"), 1);

// lib/classifier.js
var NOTIFICATION_EVENT_TYPES = Object.freeze([
  "approval_pending",
  "question_pending",
  "task_succeeded",
  "task_failed"
]);

// lib/client-policy.js
var TYPE_TO_SETTING = Object.freeze({
  approval_pending: "approvalPendingEnabled",
  question_pending: "questionPendingEnabled",
  task_succeeded: "taskSucceededEnabled",
  task_failed: "taskFailedEnabled"
});
function isNormalizedNotificationEvent(value) {
  return value !== null && typeof value == "object" && typeof value.eventId == "string" && value.eventId !== "" && NOTIFICATION_EVENT_TYPES.includes(value.type) && typeof value.sessionId == "string" && value.sessionId !== "" && Number.isFinite(value.occurredAt);
}
function eventEnabled(config, eventType) {
  if (!config || config.enabled !== !0) return !1;
  let key = TYPE_TO_SETTING[eventType];
  return key !== void 0 && config[key] === !0;
}
function shouldSurfaceEvent({ config, event, permission, visibilityState, documentHasFocus = !0, currentSessionId }) {
  return !isNormalizedNotificationEvent(event) || permission !== "granted" || !eventEnabled(config, event.type) ? !1 : visibilityState !== "visible" || documentHasFocus !== !0 || currentSessionId !== event.sessionId;
}

// src/client.js
var NS = "dshNotifications", CONFIG_PATH = "/dsh-notifications/api/config", EVENTS_PATH = "/dsh-notifications/api/events", DEFAULTS = Object.freeze({
  enabled: !0,
  approvalPendingEnabled: !0,
  questionPendingEnabled: !0,
  taskSucceededEnabled: !0,
  taskFailedEnabled: !0
}), FLAG_BY_TYPE = Object.freeze({
  approval_pending: "approvalPendingEnabled",
  question_pending: "questionPendingEnabled",
  task_succeeded: "taskSucceededEnabled",
  task_failed: "taskFailedEnabled"
}), zh = {
  title: "\u6D88\u606F\u901A\u77E5",
  description: "\u5BA1\u6279\u3001\u63D0\u95EE\u548C\u4EFB\u52A1\u7ED3\u679C\u63D0\u9192\u3002",
  master: "\u542F\u7528\u6D88\u606F\u901A\u77E5",
  masterDesc: "\u5173\u95ED\u540E\u4E0D\u4F1A\u63A5\u6536\u4EFB\u4F55\u4F1A\u8BDD\u901A\u77E5\u3002",
  approval: "\u5F85\u5BA1\u6279",
  approvalDesc: "\u4F1A\u8BDD\u7B49\u5F85\u4F60\u6279\u51C6\u64CD\u4F5C\u65F6\u901A\u77E5\u3002",
  question: "\u7B49\u5F85\u56DE\u7B54",
  questionDesc: "Agent \u53D1\u8D77\u7ED3\u6784\u5316\u63D0\u95EE\u65F6\u901A\u77E5\u3002",
  succeeded: "\u4EFB\u52A1\u6210\u529F",
  succeededDesc: "\u4EFB\u52A1\u6B63\u5E38\u5B8C\u6210\u65F6\u901A\u77E5\u3002",
  failed: "\u4EFB\u52A1\u5931\u8D25",
  failedDesc: "\u4EFB\u52A1\u5F02\u5E38\u7ED3\u675F\u65F6\u901A\u77E5\u3002",
  permission: "\u6D4F\u89C8\u5668\u6743\u9650",
  permissionDesc: "\u901A\u77E5\u6743\u9650\u7531\u5F53\u524D\u6D4F\u89C8\u5668\u6309 DSH \u5730\u5740\u7BA1\u7406\u3002",
  permissionUnsupported: "\u4E0D\u652F\u6301",
  permissionDefault: "\u672A\u6388\u6743",
  permissionGranted: "\u5DF2\u6388\u6743",
  permissionDenied: "\u5DF2\u62D2\u7EDD",
  authorize: "\u6388\u6743\u901A\u77E5",
  recheck: "\u91CD\u65B0\u68C0\u67E5",
  test: "\u53D1\u9001\u6D4B\u8BD5\u901A\u77E5",
  save: "\u4FDD\u5B58",
  saving: "\u4FDD\u5B58\u4E2D\u2026",
  reset: "\u6062\u590D\u9ED8\u8BA4",
  expand: "\u5C55\u5F00\u8BBE\u7F6E",
  collapse: "\u6536\u8D77\u8BBE\u7F6E",
  unsaved: "\u672A\u4FDD\u5B58",
  enabled: "\u5F00\u542F",
  disabled: "\u5173\u95ED",
  unavailable: "\u8BBE\u7F6E\u670D\u52A1\u4E0D\u53EF\u7528\uFF0C\u5F53\u524D\u4F7F\u7528\u9ED8\u8BA4\u914D\u7F6E\u3002",
  conflict: "\u914D\u7F6E\u5DF2\u5728\u5176\u4ED6\u7A97\u53E3\u66F4\u65B0\uFF0C\u8BF7\u91CD\u65B0\u52A0\u8F7D\u540E\u4FDD\u5B58\u3002",
  saveFailed: "\u4FDD\u5B58\u5931\u8D25\uFF0C\u8BF7\u7A0D\u540E\u91CD\u8BD5\u3002",
  permissionFailed: "\u6D4F\u89C8\u5668\u672A\u6388\u4E88\u901A\u77E5\u6743\u9650\u3002\u8BF7\u5728\u7AD9\u70B9\u8BBE\u7F6E\u4E2D\u5141\u8BB8\u901A\u77E5\u3002",
  testTitle: "DSH \u6D4B\u8BD5\u901A\u77E5",
  testBody: "\u6D88\u606F\u901A\u77E5\u63D2\u4EF6\u5DE5\u4F5C\u6B63\u5E38\u3002",
  notificationApproval: "DSH\uFF1A\u7B49\u5F85\u5BA1\u6279",
  notificationQuestion: "DSH\uFF1A\u7B49\u5F85\u56DE\u7B54",
  notificationSucceeded: "DSH\uFF1A\u4EFB\u52A1\u5DF2\u5B8C\u6210",
  notificationFailed: "DSH\uFF1A\u4EFB\u52A1\u5931\u8D25",
  conversation: "\u4F1A\u8BDD"
}, en = {
  title: "Notifications",
  description: "Alerts for approvals, questions, and task outcomes.",
  master: "Enable notifications",
  masterDesc: "Turn off to suppress all conversation notifications.",
  approval: "Approval required",
  approvalDesc: "Notify when a conversation needs your approval.",
  question: "Answer required",
  questionDesc: "Notify when the agent asks a structured question.",
  succeeded: "Task succeeded",
  succeededDesc: "Notify when a task completes successfully.",
  failed: "Task failed",
  failedDesc: "Notify when a task ends with an error.",
  permission: "Browser permission",
  permissionDesc: "Permission is managed by this browser for the current DSH origin.",
  permissionUnsupported: "Unsupported",
  permissionDefault: "Not granted",
  permissionGranted: "Granted",
  permissionDenied: "Denied",
  authorize: "Allow notifications",
  recheck: "Check again",
  test: "Send test notification",
  save: "Save",
  saving: "Saving\u2026",
  reset: "Reset defaults",
  expand: "Show settings",
  collapse: "Hide settings",
  unsaved: "Unsaved",
  enabled: "Enabled",
  disabled: "Disabled",
  unavailable: "Settings are unavailable; defaults are active.",
  conflict: "Settings changed in another window. Reload and try again.",
  saveFailed: "Settings could not be saved.",
  permissionFailed: "Notification permission was not granted. Allow it in the browser's site settings.",
  testTitle: "DSH test notification",
  testBody: "The notifications plugin is working.",
  notificationApproval: "DSH: approval required",
  notificationQuestion: "DSH: answer required",
  notificationSucceeded: "DSH: task completed",
  notificationFailed: "DSH: task failed",
  conversation: "Conversation"
}, CSS = `
.dsh-notify-card{border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-3);border-radius:12px;list-style:none;transition:border-color .16s,background .16s;color:var(--dsw-alias-label-primary)}
.dsh-notify-card:hover{border-color:var(--dsw-alias-label-dimmed)}.dsh-notify-card[data-open=true]{background:var(--dsw-alias-bg-layer-2);border-color:var(--dsw-alias-label-dimmed)}
.dsh-notify-header{appearance:none;width:100%;font:inherit;color:inherit;text-align:left;cursor:pointer;background:transparent;border:0;border-radius:12px;display:flex;align-items:center;gap:12px;padding:14px 16px}.dsh-notify-header:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:-2px}
.dsh-notify-headText{display:flex;flex-direction:column;flex:1;gap:4px;min-width:0}.dsh-notify-name{color:var(--dsw-alias-label-primary);font-size:15px;font-weight:600;line-height:1.4}.dsh-notify-description{color:var(--dsw-alias-label-tertiary);font-size:13px;line-height:1.5}
.dsh-notify-pending{white-space:nowrap;background:var(--dsw-alias-bg-module-platform);color:var(--dsw-alias-label-secondary);border-radius:999px;flex:none;padding:1px 8px;font-size:11px;font-weight:500;line-height:17px}.dsh-notify-chevron{color:var(--dsw-alias-label-tertiary);flex:none;transition:transform .16s}.dsh-notify-chevron[data-open=true]{transform:rotate(180deg)}
.dsh-notify-body{border-top:1px solid var(--dsw-alias-border-l2);margin:0 16px;padding-bottom:8px}.dsh-notify-body>.dsh-notify-row:first-child{border-top:0}
.dsh-notify-row{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 0;border-top:1px solid var(--dsw-alias-border-l2)}
.dsh-notify-rowText{display:flex;min-width:0;flex-direction:column;gap:2px}.dsh-notify-rowText strong{font-size:14px}.dsh-notify-rowText span{font-size:12px;line-height:18px;color:var(--dsw-alias-label-tertiary)}
.dsh-notify-switch{position:relative;flex:none;width:42px;height:24px;border:0;border-radius:12px;background:var(--dsw-alias-border-l2);cursor:pointer}.dsh-notify-switch[data-active=true]{background:var(--dsw-alias-state-business-primary)}.dsh-notify-switch span{position:absolute;top:3px;left:3px;width:18px;height:18px;border-radius:50%;background:#fff;transition:transform 120ms ease}.dsh-notify-switch[data-active=true] span{transform:translateX(18px)}
.dsh-notify-permission{display:flex;align-items:center;justify-content:flex-end;gap:7px;flex-wrap:wrap}.dsh-notify-badge{border-radius:5px;padding:2px 7px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px}.dsh-notify-badge[data-state=granted]{color:var(--dsw-alias-state-success-primary);background:color-mix(in srgb,var(--dsw-alias-state-success-primary) 10%,transparent)}.dsh-notify-badge[data-state=denied],.dsh-notify-badge[data-state=unsupported]{color:var(--dsw-alias-state-error-primary);background:color-mix(in srgb,var(--dsw-alias-state-error-primary) 10%,transparent)}
.dsh-notify-actions{border-top:1px solid var(--dsw-alias-border-l2);display:flex;justify-content:flex-end;align-items:center;gap:8px;padding:12px 0 4px;flex-wrap:wrap}.dsh-notify-actions button,.dsh-notify-permission button{border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:transparent;color:var(--dsw-alias-label-primary);padding:5px 14px;font:inherit;font-size:13px;line-height:1.5;cursor:pointer}.dsh-notify-actions button[data-primary=true]{border-color:transparent;background:var(--dsw-alias-label-primary);color:var(--dsw-alias-bg-layer-3)}.dsh-notify-actions button:disabled,.dsh-notify-permission button:disabled{opacity:.4;cursor:default}.dsh-notify-actions button:focus-visible,.dsh-notify-permission button:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:1px}
.dsh-notify-status{font-size:12px;line-height:18px;color:var(--dsw-alias-label-secondary);margin:0}.dsh-notify-status[data-error=true]{color:var(--dsw-alias-state-error-primary)}
@media (max-width:720px){.dsh-notify-row{align-items:flex-start;flex-direction:column;gap:8px}.dsh-notify-permission{justify-content:flex-start}}
@media (prefers-reduced-motion:reduce){.dsh-notify-card,.dsh-notify-chevron,.dsh-notify-switch span{transition:none}}
`;
function normalizeConfig(value) {
  let config = {};
  for (let key of Object.keys(DEFAULTS)) config[key] = !(value && value[key] === !1);
  return config;
}
function createConfigStore() {
  let snapshot = { value: DEFAULTS, revision: void 0, writable: !1, status: "loading" }, listeners = /* @__PURE__ */ new Set(), set = (next) => {
    snapshot = next, listeners.forEach((listener) => listener());
  }, request = async (options) => {
    let response = await fetch(CONFIG_PATH, options), body = await response.json().catch(() => ({}));
    if (!response.ok || body.ok !== !0) {
      let error = new Error(body?.error?.message || "settings request failed");
      throw error.code = body?.error?.code, error;
    }
    let next = { value: normalizeConfig(body.value), revision: body.revision, writable: body.writable === !0, status: "ready" };
    return set(next), next;
  };
  return {
    getSnapshot: () => snapshot,
    subscribe(listener) {
      return listeners.add(listener), () => listeners.delete(listener);
    },
    async load() {
      try {
        return await request({ method: "GET", credentials: "same-origin" });
      } catch {
        return set({ value: DEFAULTS, revision: void 0, writable: !1, status: "unavailable" }), snapshot;
      }
    },
    save(patch) {
      return request({
        method: "POST",
        credentials: "same-origin",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ patch, expectedRevision: snapshot.revision })
      });
    },
    reset() {
      return request({
        method: "POST",
        credentials: "same-origin",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ reset: !0, expectedRevision: snapshot.revision })
      });
    }
  };
}
function permissionOf() {
  return typeof window.Notification == "function" ? window.Notification.permission : "unsupported";
}
function randomId() {
  return globalThis.crypto?.randomUUID ? globalThis.crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
}
function createLeaderElector(options = {}) {
  let id = options.id || randomId(), now = options.now || Date.now, peers = /* @__PURE__ */ new Map([[id, now()]]), channelName = "dsh-notifications:leader", leaseKey = "dsh-notifications:leader-lease", channel;
  try {
    typeof BroadcastChannel == "function" && (channel = new BroadcastChannel(channelName));
  } catch {
  }
  let announce = () => {
    peers.set(id, now()), channel?.postMessage({ id, at: now() });
  };
  channel && (channel.onmessage = (message) => {
    let value = message.data;
    value && typeof value.id == "string" && typeof value.at == "number" && peers.set(value.id, value.at);
  }, announce());
  let timer = setInterval(announce, 2e3), localLeader = () => {
    let currentTime = now(), lease;
    try {
      lease = JSON.parse(localStorage.getItem(leaseKey) || "null");
    } catch {
    }
    if (!lease || typeof lease.expires != "number" || lease.expires <= currentTime || lease.id === id) {
      let candidate = { id, expires: currentTime + 6e3 };
      try {
        localStorage.setItem(leaseKey, JSON.stringify(candidate)), lease = JSON.parse(localStorage.getItem(leaseKey) || "null");
      } catch {
        return !0;
      }
    }
    return lease?.id === id;
  };
  return {
    isLeader() {
      if (!channel) return localLeader();
      let cutoff = now() - 6e3;
      for (let [peerId, at] of peers) at < cutoff && peers.delete(peerId);
      return peers.set(id, now()), [...peers.keys()].sort()[0] === id;
    },
    dispose() {
      clearInterval(timer), channel?.close();
      try {
        JSON.parse(localStorage.getItem(leaseKey) || "null")?.id === id && localStorage.removeItem(leaseKey);
      } catch {
      }
    }
  };
}
function sessionTitle(ctx, sessionId) {
  try {
    let session = ctx.sessions.list.getSnapshot().byId[sessionId];
    return session?.displayTitle || session?.title || sessionId;
  } catch {
    return sessionId;
  }
}
function notificationTitle(t, type) {
  return t({
    approval_pending: "notificationApproval",
    question_pending: "notificationQuestion",
    task_succeeded: "notificationSucceeded",
    task_failed: "notificationFailed"
  }[type]);
}
function createNotificationController(ctx, store, t) {
  let seen = /* @__PURE__ */ new Set(), leader = createLeaderElector(), source, remember = (id) => {
    seen.add(id), seen.size > 512 && seen.delete(seen.values().next().value);
  }, shouldNotify = (event) => {
    let current;
    try {
      current = ctx.sessions.list.getSnapshot().current;
    } catch {
    }
    return shouldSurfaceEvent({
      config: store.getSnapshot().value,
      event,
      permission: permissionOf(),
      visibilityState: document.visibilityState,
      documentHasFocus: document.hasFocus(),
      currentSessionId: current
    });
  }, openSession = (sessionId) => {
    window.focus();
    try {
      ctx.sessions.list.getSnapshot().byId[sessionId] !== void 0 && ctx.sessions.open?.(sessionId);
    } catch {
    }
  }, handle = (event) => {
    if (!event || typeof event.eventId != "string" || typeof event.sessionId != "string" || !(event.type in FLAG_BY_TYPE) || seen.has(event.eventId) || (remember(event.eventId), !leader.isLeader() || !shouldNotify(event))) return;
    let notification = new window.Notification(notificationTitle(t, event.type), {
      body: `${t("conversation")}\uFF1A${sessionTitle(ctx, event.sessionId)}`,
      tag: event.eventId,
      renotify: !1
    });
    notification.onclick = () => {
      openSession(event.sessionId), notification.close();
    };
  };
  return {
    start() {
      return typeof EventSource != "function" ? () => leader.dispose() : (source = new EventSource(EVENTS_PATH), source.addEventListener("notification", (message) => {
        try {
          handle(JSON.parse(message.data));
        } catch (error) {
          console.warn("[dsh-notifications] invalid event", error);
        }
      }), () => {
        source?.close(), leader.dispose();
      });
    },
    test() {
      if (permissionOf() !== "granted") return !1;
      let notification = new window.Notification(t("testTitle"), { body: t("testBody"), tag: `dsh-notifications:test:${Date.now()}` });
      return notification.onclick = () => {
        window.focus(), notification.close();
      }, !0;
    }
  };
}
function useStore(store) {
  let [snapshot, setSnapshot] = import_react.default.useState(store.getSnapshot());
  return import_react.default.useEffect(() => store.subscribe(() => setSnapshot(store.getSnapshot())), [store]), snapshot;
}
function ToggleRow({ title, description, checked, onChange }) {
  let h = import_react.default.createElement;
  return h(
    "div",
    { className: "dsh-notify-row" },
    h("div", { className: "dsh-notify-rowText" }, h("strong", null, title), h("span", null, description)),
    h("button", { type: "button", className: "dsh-notify-switch", role: "switch", "aria-checked": checked, "data-active": checked ? "true" : void 0, onClick: () => onChange(!checked) }, h("span", null))
  );
}
function Chevron({ open }) {
  let h = import_react.default.createElement;
  return h("svg", {
    className: "dsh-notify-chevron",
    "data-open": open ? "true" : void 0,
    width: 14,
    height: 14,
    viewBox: "0 0 14 14",
    fill: "none",
    "aria-hidden": "true"
  }, h("path", {
    d: "M3 5.25 7 9.25 11 5.25",
    stroke: "currentColor",
    strokeWidth: 1.4,
    strokeLinecap: "round",
    strokeLinejoin: "round"
  }));
}
function configsEqual(left, right) {
  return Object.keys(DEFAULTS).every((key) => left[key] === right[key]);
}
function SettingsCard({ store, controller, t }) {
  let snapshot = useStore(store), [draft, setDraft] = import_react.default.useState(snapshot.value), [permission, setPermission] = import_react.default.useState(permissionOf()), [state, setState] = import_react.default.useState({ saving: !1, error: "" }), [open, setOpen] = import_react.default.useState(!1);
  import_react.default.useEffect(() => setDraft(snapshot.value), [snapshot.value]);
  let dirty = !configsEqual(draft, snapshot.value), patch = (key, value) => setDraft((current) => ({ ...current, [key]: value })), authorize = async () => {
    setState((current) => ({ ...current, error: "" }));
    try {
      permissionOf() === "default" && await window.Notification.requestPermission();
      let next = permissionOf();
      setPermission(next), next !== "granted" && setState((current) => ({ ...current, error: t("permissionFailed") }));
    } catch {
      setPermission(permissionOf()), setState((current) => ({ ...current, error: t("permissionFailed") }));
    }
  }, save = async () => {
    setState({ saving: !0, error: "" });
    try {
      await store.save(draft), setState({ saving: !1, error: "" });
    } catch (error) {
      setState({ saving: !1, error: error?.code === "settings-conflict" ? t("conflict") : t("saveFailed") }), await store.load();
    }
  }, reset = async () => {
    setState({ saving: !0, error: "" });
    try {
      await store.reset(), setState({ saving: !1, error: "" });
    } catch {
      setState({ saving: !1, error: t("saveFailed") });
    }
  }, h = import_react.default.createElement;
  return h(
    "li",
    { className: "dsh-notify-card", "data-open": open ? "true" : void 0 },
    h(
      "button",
      {
        type: "button",
        className: "dsh-notify-header",
        "aria-expanded": open,
        "aria-label": `${t(open ? "collapse" : "expand")}\uFF1A${t("title")}`,
        onClick: () => setOpen((current) => !current)
      },
      h(
        "span",
        { className: "dsh-notify-headText" },
        h("span", { className: "dsh-notify-name" }, t("title")),
        h("span", { className: "dsh-notify-description" }, t("description"))
      ),
      dirty ? h("span", { className: "dsh-notify-pending" }, t("unsaved")) : null,
      h(Chevron, { open })
    ),
    open ? h(
      "div",
      { className: "dsh-notify-body" },
      h(ToggleRow, { title: t("master"), description: t("masterDesc"), checked: draft.enabled, onChange: (value) => patch("enabled", value) }),
      h(ToggleRow, { title: t("approval"), description: t("approvalDesc"), checked: draft.approvalPendingEnabled, onChange: (value) => patch("approvalPendingEnabled", value) }),
      h(ToggleRow, { title: t("question"), description: t("questionDesc"), checked: draft.questionPendingEnabled, onChange: (value) => patch("questionPendingEnabled", value) }),
      h(ToggleRow, { title: t("succeeded"), description: t("succeededDesc"), checked: draft.taskSucceededEnabled, onChange: (value) => patch("taskSucceededEnabled", value) }),
      h(ToggleRow, { title: t("failed"), description: t("failedDesc"), checked: draft.taskFailedEnabled, onChange: (value) => patch("taskFailedEnabled", value) }),
      h(
        "div",
        { className: "dsh-notify-row" },
        h("div", { className: "dsh-notify-rowText" }, h("strong", null, t("permission")), h("span", null, t("permissionDesc"))),
        h(
          "div",
          { className: "dsh-notify-permission" },
          h("span", { className: "dsh-notify-badge", "data-state": permission }, t(`permission${permission[0]?.toUpperCase()}${permission.slice(1)}`)),
          h("button", { type: "button", disabled: permission === "unsupported" || permission === "granted", onClick: authorize }, t("authorize")),
          h("button", { type: "button", onClick: () => setPermission(permissionOf()) }, t("recheck")),
          h("button", { type: "button", disabled: permission !== "granted", onClick: () => controller.test() }, t("test"))
        )
      ),
      snapshot.status === "unavailable" ? h("p", { className: "dsh-notify-status", "data-error": "true" }, t("unavailable")) : null,
      state.error ? h("p", { className: "dsh-notify-status", "data-error": "true" }, state.error) : null,
      h(
        "div",
        { className: "dsh-notify-actions" },
        h("button", { type: "button", "data-primary": "true", disabled: state.saving || !snapshot.writable || !dirty, onClick: save }, state.saving ? t("saving") : t("save")),
        h("button", { type: "button", disabled: state.saving || !snapshot.writable, onClick: reset }, t("reset"))
      )
    ) : null
  );
}
var inject = ["slots", "locale", "sessions"];
function apply(ctx) {
  let store = createConfigStore();
  ctx.effect(() => ctx.locale.register(NS, { zh, en }), "dsh-notifications: locale");
  let t = ctx.locale.bind(NS), controller = createNotificationController(ctx, store, t);
  ctx.effect(() => {
    let tag = document.createElement("style");
    return tag.dataset.plugin = "dsh-notifications", tag.textContent = CSS, document.head.appendChild(tag), () => tag.remove();
  }, "dsh-notifications: styles"), ctx.effect(() => controller.start(), "dsh-notifications: event stream"), ctx.slots.inject("settings.plugin.item", () => ctx.slots.register({
    name: "settings.plugin.item",
    id: "notifications",
    order: 70,
    inject: () => ({ store, controller, t })
  }, SettingsCard)), store.load();
}

    return module.exports;
  }
});
