import { build } from "esbuild";
import { readFile, writeFile, rm } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const temp = join(root, ".client.bundle.cjs");
const client = join(root, "client.js");

await build({
  entryPoints: [join(root, "src/client.js")],
  outfile: temp,
  bundle: true,
  format: "cjs",
  platform: "browser",
  target: ["es2020"],
  external: ["react"],
  legalComments: "none",
  sourcemap: false,
  minifySyntax: true,
  logLevel: "info"
});

const body = await readFile(temp, "utf8");
const output = `// Generated by scripts/build.mjs. Do not edit by hand.\nwindow.__ModuleLoader__.load({\n  id: "dsh-notifications",\n  factory: (require) => {\n    var module = { exports: {} };\n    var exports = module.exports;\n    ${body}\n    return module.exports;\n  }\n});\n`;
await writeFile(client, output, "utf8");
await rm(temp, { force: true });
console.log(`wrote ${client}`);
